Feature: Replace `clean` commands with `reset` and `purge` commands
astriaorg/astria-cli-go pull request #76
Opened 2024-05-02 22:13 UTC by sambukowski

The existing workflow for initializing, cleaning/reseting data, and running or re-running for the cli wasn't particularly clear. Specifically the user flow for when you needed to re-run `init` after a given command and that running `init` would reset all config.
`init` now ignores all files that currently exist, so a user can make changes to their env files or other config and re-run `init` without fear of those changes being removed.
The existing `clean` commands have been removed and replace with more descriptive `reset` and `purge` commands.
The new user flow is as follows: 
- if you run a `reset` command, you don't need to run `init` again before `run`.
- if you run a `purge` command, you do need to run `init` again before `run`

`reset` commands return the data to their initial state, as though `init` was run for the first time.
`purge` commands simply delete the specified data

Added commands:
`dev reset config` -> reset cometbft configs
`dev reset env` -> reset env files
`dev reset state` -> reset the state
`dev purge binaries` -> delete the downloaded binaries
`dev purge all` -> delete an instance

closes #71

2024-05-02 23:15 UTC, steezeburger requested changes

2024-05-02 23:15 UTC, steezeburger commented on cmd/devtools/purge.go
> +// resetCmd represents the root reset command
update comment

2024-05-02 23:15 UTC, steezeburger commented on cmd/devtools/purge.go
> +	Long:   "Delete all binaries for a given instance.",
I don't think you need to include both Short and Long if they're the same

2024-05-02 23:15 UTC, steezeburger commented on cmd/devtools/purge.go
> +	purgeCmd.PersistentFlags().StringP("instance", "i", DefaultInstanceName, "Choose the target instance for resetting.")
```suggestion
	purgeCmd.PersistentFlags().StringP("instance", "i", DefaultInstanceName, "Choose the target instance for purging.")
```

2024-05-02 23:15 UTC, steezeburger commented on cmd/devtools/reset.go
> +	recreateCometbftAndSequencerGenesisData(localConfigDir)
We should reorganize where this function lives now that it's shared.

Maybe we move all the embedded and config file functionality to its own file in `cmd/devtools`, maybe `confighelpers.go` or something?

2024-05-02 23:15 UTC, steezeburger commented on cmd/devtools/reset.go
> +	recreateCometbftAndSequencerGenesisData(localConfigDir)
Tangential, but I noticed a few misspellings, `instancDir`, that you can fix when you move things, but I can't comment on that section of the code.

2024-05-03 16:32 UTC, sambukowski commented on cmd/devtools/init.go
> +func copyFile(src, dst string) error {
Both `src`, and `dst` are strings. After doing a little digging it seems this is the more idiomatic way of having multiple arguments of the same type in go. But we're also not being consistent with this in many places and should probably update that.

2024-05-03 17:31 UTC, steezeburger commented on cmd/devtools/init.go
> +func copyFile(src, dst string) error {
Why would src be anything but a string? That's what os.Open takes.

2024-05-03 17:36 UTC, steezeburger requested changes

2024-05-03 21:32 UTC, steezeburger approved these changes

2024-05-03 21:42 UTC, merged